version: '3'

services:
  web:
    build: .
    image: ruby:3.1.2
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - '.:/app'
      - 'rubygems:/usr/local/bundle'
      - 'node_modules:/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${PGPASSWORD}

  db:
    image: postgres:15
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${PGPASSWORD}

volumes:
  rubygems:
  pgdata:
  node_modules:
